[package]
name = "guests"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
serde = "1.0.214"

[profile.release]
lto = "thin"
