/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { ImageID, ImageIDInterface } from "../ImageID";

const _abi = [
  {
    inputs: [],
    name: "FINALIZE_FIBONACHI_ID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60df610051600b82828239805160001a6073146044577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063da548322146038575b600080fd5b603e6052565b604051604991906090565b60405180910390f35b7f1643c9c24b16f05f541abcff1ddae52514fab31304f75ac2923156b84533d0b960001b81565b6000819050919050565b608a816079565b82525050565b600060208201905060a360008301846083565b9291505056fea264697066735822122032cd12ffa58d7669e4ff0b8709ea39d2e81b17c53314d9d179acb6753795105964736f6c634300081b0033";

type ImageIDConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImageIDConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImageID__factory extends ContractFactory {
  constructor(...args: ImageIDConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ImageID & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ImageID__factory {
    return super.connect(runner) as ImageID__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImageIDInterface {
    return new Interface(_abi) as ImageIDInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ImageID {
    return new Contract(address, _abi, runner) as unknown as ImageID;
  }
}
