[package]
name = "apps"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.1.2" }
risc0-ethereum-contracts = { version = "1.1.4" }
risc0-groth16 = { version = "1.1.2" }

tracing-subscriber = { version = "0.3", features = ["env-filter"] }

methods = { workspace = true }
ethers = { version = "2.0.14" }
dotenv = "0.15"
tokio = { version = "1.10", features = ["full"] }
serde = { workspace = true }
rand = "0.8.5"
sha2 = "0.10.8"
anyhow = "1.0.44"
hex = "0.4.3"
