[package]
name = "apps"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "1.1.2" }
risc0-ethereum-contracts = { version = "1.1.4" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

ethers = { version = "2.0.14"}
dotenv = "0.15" 
tokio = { version = "1.10", features = ["full"] }
serde = "1.0"
rand = "0.8.5"
sha2 = "0.10.8"
anyhow = "1.0.44"


